-- Auto-generated from SQLite schema.

-- Source: C:/codigos_fuente/cfdi_app/cfdi-api/database/contabilidad.sqlite

-- Target: PostgreSQL 14+



BEGIN;



CREATE EXTENSION IF NOT EXISTS pgcrypto;



CREATE TABLE catalogo_tipo_declaracion (
    clave TEXT PRIMARY KEY,
    descripcion TEXT NOT NULL,
    activo BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE catalogo_tipo_persona (
    clave TEXT PRIMARY KEY,
    descripcion TEXT NOT NULL
);

CREATE TABLE declaraciones_pdf (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    year BIGINT NOT NULL,
    month BIGINT NOT NULL,
    rfc VARCHAR(20),
    folio VARCHAR(80),
    fecha_presentacion TIMESTAMP WITHOUT TIME ZONE,
    sha256 VARCHAR(64) NOT NULL,
    filename VARCHAR(260) NOT NULL,
    original_name VARCHAR(260),
    num_pages BIGINT,
    text_excerpt TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    saldo_a_favor NUMERIC(18,6) NOT NULL DEFAULT 0,
    saldo_a_pagar NUMERIC(18,6) NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE facturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid VARCHAR(40),
    version VARCHAR(10),
    tipo_comprobante VARCHAR(5),
    fecha_emision TIMESTAMP WITHOUT TIME ZONE,
    year_emision BIGINT,
    month_emision BIGINT,
    naturaleza VARCHAR(12),
    emisor_rfc VARCHAR(20),
    emisor_nombre VARCHAR(300),
    receptor_rfc VARCHAR(20),
    receptor_nombre VARCHAR(300),
    uso_cfdi VARCHAR(10),
    moneda VARCHAR(10),
    metodo_pago VARCHAR(10),
    forma_pago VARCHAR(10),
    subtotal NUMERIC(18, 6),
    descuento NUMERIC(18, 6),
    total NUMERIC(18, 6),
    total_trasladados NUMERIC(18, 6),
    total_retenidos NUMERIC(18, 6),
    xml_text TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE platform_rfcs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rfc VARCHAR(20) NOT NULL,
    nombre VARCHAR(300),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE retenciones_plataforma (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid VARCHAR(40),
    version VARCHAR(10),
    fecha_exp TIMESTAMP WITHOUT TIME ZONE,
    ejercicio BIGINT,
    mes_ini BIGINT,
    mes_fin BIGINT,
    emisor_rfc VARCHAR(20),
    emisor_nombre VARCHAR(300),
    receptor_rfc VARCHAR(20),
    receptor_nombre VARCHAR(300),
    monto_tot_operacion NUMERIC(18, 6),
    monto_tot_grav NUMERIC(18, 6),
    monto_tot_exent NUMERIC(18, 6),
    monto_tot_ret NUMERIC(18, 6),
    periodicidad VARCHAR(10),
    num_serv BIGINT,
    mon_tot_serv_siva NUMERIC(18, 6),
    total_iva_trasladado NUMERIC(18, 6),
    total_iva_retenido NUMERIC(18, 6),
    total_isr_retenido NUMERIC(18, 6),
    dif_iva_entregado_prest_serv NUMERIC(18, 6),
    mon_total_por_uso_plataforma NUMERIC(18, 6),
    xml_text TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE rfc_phones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone VARCHAR(32) NOT NULL,
    rfc VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE sat_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rfc VARCHAR(20) NOT NULL,
    pfx_encrypted BYTEA NOT NULL,
    pfx_password_encrypted VARCHAR(512),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE sat_descargas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rfc VARCHAR(20) NOT NULL,
    kind VARCHAR(20) NOT NULL,
    tipo_solicitud VARCHAR(20) NOT NULL,
    anio_filtro BIGINT,
    mes_filtro BIGINT,
    id_solicitud VARCHAR(80),
    estado VARCHAR(30) NOT NULL,
    paquetes JSONB NOT NULL,
    link_descarga VARCHAR(500),
    zip_path VARCHAR(500),
    attempts BIGINT NOT NULL,
    next_check_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    codigo_estado VARCHAR(20),
    mensaje_estado TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(80) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL,
    last_login_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE catalogo_uso_cfdi_deduccion (
    clave TEXT PRIMARY KEY,
    descripcion TEXT NOT NULL,
    tipo_declaracion_clave TEXT NOT NULL,
    activo BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_uso_cfdi_tipo_decl
      FOREIGN KEY (tipo_declaracion_clave)
      REFERENCES catalogo_tipo_declaracion (clave)
);

CREATE TABLE catalogo_regimen_fiscal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_persona_clave TEXT NOT NULL,
    clave TEXT NOT NULL,
    descripcion TEXT NOT NULL,
    activo BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT fk_catalogo_regimen_tipo_persona FOREIGN KEY (tipo_persona_clave) REFERENCES catalogo_tipo_persona (clave),
    CONSTRAINT ux_regimen_fiscal_tipo_clave UNIQUE (tipo_persona_clave, clave)
);

CREATE TABLE conceptos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    factura_id BIGINT NOT NULL,
    clave_prod_serv VARCHAR(30),
    cantidad NUMERIC(18, 6),
    clave_unidad VARCHAR(10),
    descripcion VARCHAR(1000),
    valor_unitario NUMERIC(18, 6),
    importe NUMERIC(18, 6),
    objeto_imp VARCHAR(5),
    PRIMARY KEY (id),
    FOREIGN KEY(factura_id) REFERENCES facturas (id)
);

CREATE TABLE pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    factura_id BIGINT NOT NULL,
    fecha_pago TIMESTAMP WITHOUT TIME ZONE,
    year_pago BIGINT,
    month_pago BIGINT,
    monto NUMERIC(18, 6),
    moneda_p VARCHAR(10),
    forma_pago_p VARCHAR(10),
    PRIMARY KEY (id),
    FOREIGN KEY(factura_id) REFERENCES facturas (id)
);

CREATE TABLE regimen_declaracion_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regimen_fiscal_id BIGINT NOT NULL,
    tipo_declaracion_clave TEXT NOT NULL,
    activo BIGINT NOT NULL DEFAULT 1,
    incluir_acumulado_mensual_en_anual BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_config_regimen
      FOREIGN KEY (regimen_fiscal_id)
      REFERENCES catalogo_regimen_fiscal (id),
    CONSTRAINT fk_config_tipo_decl
      FOREIGN KEY (tipo_declaracion_clave)
      REFERENCES catalogo_tipo_declaracion (clave),
    CONSTRAINT ux_config_regimen_tipo
      UNIQUE (regimen_fiscal_id, tipo_declaracion_clave)
);

CREATE TABLE rfcs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rfc VARCHAR(20) NOT NULL,
    regimen_fiscal_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(regimen_fiscal_id) REFERENCES catalogo_regimen_fiscal(id)
);

CREATE TABLE regimen_declaracion_config_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id BIGINT NOT NULL,
    uso_cfdi_clave TEXT NOT NULL,
    orden BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_config_detalle_config
      FOREIGN KEY (config_id)
      REFERENCES regimen_declaracion_config (id)
      ON DELETE CASCADE,
    CONSTRAINT fk_config_detalle_uso
      FOREIGN KEY (uso_cfdi_clave)
      REFERENCES catalogo_uso_cfdi_deduccion (clave),
    CONSTRAINT ux_config_detalle
      UNIQUE (config_id, uso_cfdi_clave)
);

CREATE TABLE user_rfcs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    rfc_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_user_rfcs_new_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_rfcs_new_rfc FOREIGN KEY (rfc_id) REFERENCES rfcs (id)
);

CREATE INDEX ix_conceptos_factura_id ON conceptos (factura_id);

CREATE INDEX ix_config_detalle_config
  ON regimen_declaracion_config_detalle (config_id);

CREATE INDEX ix_config_regimen
  ON regimen_declaracion_config (regimen_fiscal_id);

CREATE INDEX ix_declaraciones_pdf_folio ON declaraciones_pdf (folio);

CREATE INDEX ix_declaraciones_pdf_month ON declaraciones_pdf (month);

CREATE INDEX ix_declaraciones_pdf_rfc ON declaraciones_pdf (rfc);

CREATE UNIQUE INDEX ix_declaraciones_pdf_sha256 ON declaraciones_pdf (sha256);

CREATE INDEX ix_declaraciones_pdf_year ON declaraciones_pdf (year);

CREATE INDEX ix_facturas_emisor_rfc ON facturas (emisor_rfc);

CREATE INDEX ix_facturas_fecha_emision ON facturas (fecha_emision);

CREATE INDEX ix_facturas_month_emision ON facturas (month_emision);

CREATE INDEX ix_facturas_naturaleza ON facturas (naturaleza);

CREATE INDEX ix_facturas_receptor_rfc ON facturas (receptor_rfc);

CREATE INDEX ix_facturas_tipo_comprobante ON facturas (tipo_comprobante);

CREATE INDEX ix_facturas_uuid ON facturas (uuid);

CREATE INDEX ix_facturas_year_emision ON facturas (year_emision);

CREATE INDEX ix_pagos_factura_id ON pagos (factura_id);

CREATE INDEX ix_pagos_fecha_pago ON pagos (fecha_pago);

CREATE INDEX ix_pagos_month_pago ON pagos (month_pago);

CREATE INDEX ix_pagos_year_pago ON pagos (year_pago);

CREATE UNIQUE INDEX ix_platform_rfcs_rfc ON platform_rfcs (rfc);

CREATE INDEX ix_retenciones_plataforma_ejercicio ON retenciones_plataforma (ejercicio);

CREATE INDEX ix_retenciones_plataforma_emisor_rfc ON retenciones_plataforma (emisor_rfc);

CREATE INDEX ix_retenciones_plataforma_fecha_exp ON retenciones_plataforma (fecha_exp);

CREATE INDEX ix_retenciones_plataforma_mes_fin ON retenciones_plataforma (mes_fin);

CREATE INDEX ix_retenciones_plataforma_mes_ini ON retenciones_plataforma (mes_ini);

CREATE INDEX ix_retenciones_plataforma_receptor_rfc ON retenciones_plataforma (receptor_rfc);

CREATE INDEX ix_retenciones_plataforma_uuid ON retenciones_plataforma (uuid);

CREATE UNIQUE INDEX ix_rfc_phones_phone ON rfc_phones (phone);

CREATE INDEX ix_rfc_phones_rfc ON rfc_phones (rfc);

CREATE INDEX ix_rfcs_regimen_fiscal_id ON rfcs (regimen_fiscal_id);

CREATE UNIQUE INDEX ix_rfcs_rfc ON rfcs (rfc);

CREATE UNIQUE INDEX ix_sat_credentials_rfc ON sat_credentials (rfc);

CREATE INDEX ix_sat_descargas_anio_filtro ON sat_descargas (anio_filtro);

CREATE INDEX ix_sat_descargas_estado ON sat_descargas (estado);

CREATE INDEX ix_sat_descargas_id_solicitud ON sat_descargas (id_solicitud);

CREATE INDEX ix_sat_descargas_mes_filtro ON sat_descargas (mes_filtro);

CREATE INDEX ix_sat_descargas_rfc ON sat_descargas (rfc);

CREATE INDEX ix_user_rfcs_rfc_id ON user_rfcs (rfc_id);

CREATE INDEX ix_user_rfcs_user_id ON user_rfcs (user_id);

CREATE UNIQUE INDEX ix_users_email ON users (email);

CREATE UNIQUE INDEX ix_users_username ON users (username);

CREATE INDEX ix_uso_cfdi_tipo_decl
  ON catalogo_uso_cfdi_deduccion (tipo_declaracion_clave);

CREATE UNIQUE INDEX ux_user_rfc ON user_rfcs (user_id, rfc_id);



-- Generic trigger to maintain updated_at columns
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_catalogo_tipo_declaracion_updated_at ON catalogo_tipo_declaracion;
CREATE TRIGGER trg_catalogo_tipo_declaracion_updated_at
BEFORE UPDATE ON catalogo_tipo_declaracion
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_catalogo_uso_cfdi_deduccion_updated_at ON catalogo_uso_cfdi_deduccion;
CREATE TRIGGER trg_catalogo_uso_cfdi_deduccion_updated_at
BEFORE UPDATE ON catalogo_uso_cfdi_deduccion
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_regimen_declaracion_config_updated_at ON regimen_declaracion_config;
CREATE TRIGGER trg_regimen_declaracion_config_updated_at
BEFORE UPDATE ON regimen_declaracion_config
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_rfcs_updated_at ON rfcs;
CREATE TRIGGER trg_rfcs_updated_at
BEFORE UPDATE ON rfcs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_sat_credentials_updated_at ON sat_credentials;
CREATE TRIGGER trg_sat_credentials_updated_at
BEFORE UPDATE ON sat_credentials
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_sat_descargas_updated_at ON sat_descargas;
CREATE TRIGGER trg_sat_descargas_updated_at
BEFORE UPDATE ON sat_descargas
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();



COMMIT;

